---

title: "OKR Best Desktop"
copyright: "© 2024-present OKR Best. All Rights Reserved. Based on Mattermost Desktop © 2016-present Mattermost, Inc. See LICENSE.txt for license information."
description: "This document includes a list of open source components used in OKR Best Desktop, including those that have been modified."
reviewers: 
  - okrbest/release-managers
  - okrbest/team-desktop
search:
  - "package.json"
additionalDependencies:
  - wix
includeDevDependencies: true
...
