name: Snyk - Software Bill of Materials (SBOM)
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        type: string
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: okrbest/actions-workflows/.github/workflows/snyk-sbom.yml@772f661c17447c1eef9b0f545b2601fd8e5ed6e4
    secrets: inherit
    with:
      is_monorepo: false
      tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
